pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps { checkout scm }
        }

        stage('Install Dependencies') {
            steps { sh 'npm install' }
        }

        stage('Run Tests') {
            steps { sh 'npm test' }
        }

        stage('Build & Deploy Docker') {
            steps {
                script {
                    sh 'docker build -t my-node-app:latest .'
                    sh 'docker run -d -p 3000:3000 my-node-app:latest'
                }
            }
        }
    }
}

